
---
apiVersion: v1
kind: Service
metadata:
  name: solido
  namespace: solido
  labels:
    app: solido
spec:
  ports:
    - port: 8899
      name: rpc
      protocol: TCP
    - port: 9900
      name: faucet
      protocol: TCP
  clusterIP: None
  selector:
    app: solido
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solido
  namespace: solido
spec:
  selector:
    matchLabels:
      app: solido
  serviceName: solido
  replicas: 1
  template:
    metadata:
      labels:
        app: solido
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: solana
          image: chorusone/solido
          command:
            - solana-test-validator
            - --log
          ports:
            - containerPort: 8001
              name: gossip
              protocol: UDP
            - containerPort: 8003
              name: tpu
              protocol: UDP
            - containerPort: 8004
              name: tpufwd
              protocol: UDP
            - containerPort: 8000
              name: tvu
              protocol: UDP
            - containerPort: 8002
              name: tvufwd
              protocol: UDP
            - containerPort: 8006
              name: repair
              protocol: UDP
            - containerPort: 8007
              name: serverepair
              protocol: UDP
            - containerPort: 8899
              name: rpc
              protocol: TCP
            - containerPort: 8900
              name: pubsub
              protocol: TCP
            - containerPort: 9900
              name: faucet
              protocol: TCP
              #          readinessProbe:
              #httpGet:
              #port: rpc
              #path: /health
