{
 "title": "Lido for Solana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SOL Managed by Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "sum(solido_balance_sol) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SOL managed by validator",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "sum(solido_balance_sol{vote_account != \"\"}) by (vote_account)",
     "legendFormat": "{{vote_account}}"
    },
    {
     "expr": "solido_balance_sol{status=\"reserve\"}",
     "legendFormat": "reserve"
    }
   ]
  },
  {
   "title": "Maintainer Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(solido_maintenance_polls_total[5m])",
     "legendFormat": "5m poll rate"
    },
    {
     "expr": "rate(solido_maintenance_errors_total[5m])",
     "legendFormat": "5m error rate"
    }
   ]
  },
  {
   "title": "5m Operations Executed",
   "type": "timeseries",
   "description": "Which operations were executed in a 5-minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(solido_maintenance_transactions_total[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Exchange Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "sum(solido_balance_sol) / sum(solido_token_supply_st_sol)",
     "legendFormat": "momentary price of stSOL"
    },
    {
     "expr": "solido_exchange_rate_balance_sol / soldio_exchange_rate_supply_st_sol",
     "legendFormat": "epoch price of stSOL"
    }
   ]
  },
  {
   "title": "Maintainer balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    { "expr": "solido_maintainer_balance_sol", "legendFormat": "{{maintainer_address}}" }
   ]
  },
  {
   "title": "Solana Block Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / (rate(solido_solana_block_height[10m]) and (solido_solana_block_height offset 27m)) # The rate will be wrong when there are holes in the data, compensate by adding an and with an offset timeseries, to make the result null at times where the rate would be wrong. For reasons that I don’t understand, the offset needed for that is not the window size of 10m, it’s this magic 27m ... which is 10m + 17m.",
     "legendFormat": "10m avg block time"
    },
    {
     "expr": "1 / (rate(solido_solana_block_height[30m]) and (solido_solana_block_height offset 47m)) # The magic offset here that makes the artifact at the start go away, is again the window size, plus 17m.",
     "legendFormat": "30m avg block time"
    }
   ]
  },
  {
   "title": "Deposits",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(solido_deposit_amount_sol_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}