FROM rust:slim-buster@sha256:bbf94ba964b3d9a47600d8f5e2275fc461df300300216dc9f173e42e46300f74 as build

ENV SOLIDOBUILDPATH="/solido-build"

# Install Solana tools
RUN apt -y update \
    && apt -y install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make curl python3


# Make dirs for build artefacts
RUN mkdir -p $SOLIDOBUILDPATH

COPY . $SOLIDOBUILDPATH/

# Build packages
RUN cd $SOLIDOBUILDPATH \
    && cargo build --release --bin solido

FROM debian:stable-slim@sha256:463cabea60abc361ab670570fe30549a6531cd9af4a1b8577b1c93e9b5a1d369

RUN useradd -m -d /solido solido
USER solido

# Copy from build container
COPY --from=build /solido-build/target/release/ /solido

# Remove build folder
RUN rm -rf /solido/build

WORKDIR /solido
