[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/stake-pool"
license = "Apache-2.0"
name = "spl-stake-pool-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.0.1"

[dependencies]
borsh = "0.8"
clap = "2.33.3"
serde_json = "1.0.62"
solana-account-decoder = "1.6.6"
solana-clap-utils = "1.6.6"
solana-cli-config = "1.6.6"
solana-client = "1.6.6"
solana-logger = "1.6.6"
solana-sdk = "1.6.6"
solana-program = "1.6.6"
spl-stake-pool = { path="../program", features = [ "no-entrypoint" ] }
spl-token = { path="../../token/program", features = [ "no-entrypoint" ]  }
bs58 = "0.4.0"
bincode = "1.3.1"
lazy_static = "1.4.0"

[[bin]]
name = "spl-stake-pool"
path = "src/main.rs"
